version: '3.4'

services:
  nodetypescript:
    image: nodetypescript
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:5001
